### ISSUE TITLE
Any updates? 

### ISSUE THREAD

**Issue by csrqli** [Anttwo/SCONE#1]
Thanks for the great work! Would you provide some updates regarding training data generation scripts?

**Comment by Anttwo** [comment]
Hello Rlee719,

Thank you so much for your kind comment!

Indeed, I did not update the SCONE repo, I am really sorry for that. But there is actually a good reason for this!

We released a new model called [MACARONS (CVPR 2023)](https://github.com/Anttwo/MACARONS) which is a direct improvement of SCONE. 
**MACARONS adapts the approach from SCONE to a fully self-supervised pipeline**: It learns simultaneously to explore and reconstruct 3D scenes from RGB images only (there is no need for 3D ground truth data nor depth sensors).

The codebase of MACARONS **includes an entire, updated version of SCONE's code** as well as **detailed instructions for generating the ShapeNet training data** we used for SCONE.

You should find everything you are looking for in MACARONS' repo!

I will update the README file in the SCONE's repo to let other users know about this.

Thank you!

**Comment by csrqli** [comment]
Cool! Congrats and thank you! 😃
