### ISSUE TITLE
Usage of the repository

### ISSUE THREAD

**Issue by SvyJ** [Anttwo/SCONE#2]
Could you please add more code usage details as soon as possible, thank you!

**Comment by Anttwo** [comment]
Hello SvyJ,

We actually released a new model called [MACARONS (CVPR 2023)](https://github.com/Anttwo/MACARONS) which is a direct improvement of SCONE.
MACARONS adapts the approach from SCONE to a fully self-supervised pipeline: It learns simultaneously to explore and reconstruct 3D scenes from RGB images only (there is no need for 3D ground truth data nor depth sensors).

The codebase of MACARONS includes an entire, updated version of SCONE's code as well as detailed instructions for generating the ShapeNet training data we used for SCONE.

I think you should find everything you are looking for in MACARONS' repo!

If not, feel free to tell me in details what you would like to know about SCONE.

Best!
